// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdUVyBiL8I4p4_DhgjGGAscXzex6HMh2I',
    appId: '1:454683126074:web:e3d0b7d5bc505dc7bbc803',
    messagingSenderId: '454683126074',
    projectId: 'sunco-physics',
    authDomain: 'sunco-physics.firebaseapp.com',
    storageBucket: 'sunco-physics.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtnmjvn_bGJwY6wqcElRnyXbOyAZetzc',
    appId: '1:454683126074:android:f06c1b1bd4c2bdb6bbc803',
    messagingSenderId: '454683126074',
    projectId: 'sunco-physics',
    storageBucket: 'sunco-physics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnIB8q6bgYQ_TL9uA5_kWZn6QyfBSK_NQ',
    appId: '1:454683126074:ios:db4312615c4cfdcdbbc803',
    messagingSenderId: '454683126074',
    projectId: 'sunco-physics',
    storageBucket: 'sunco-physics.firebasestorage.app',
    iosBundleId: 'com.example.suncoPhysics',
  );
}
